Portfolio main page
Anwaar12/My-portfolio pull request #1
Opened 2022-09-27 14:38 UTC by Anwaar12

I created a new GitHub repo
I created a new branch according to the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) rules.
[I Added a .gitignore file.
I Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
I added a descriptive README file to my project
I Added3 files (each one in a separate commit:
I created A .html file that includes information about me and link to my social media accounts.I put picture to some of my project which I made and also links to it and after that I put information about my development career.
I created A .css file that includes styles to the icons of the social media apps. In this, I use flexbox to position elements and add styles to logos and other content. I use grid to place element on page.
I added A test.md file with the text "This file should be ignored by git".
I made sure that the last file is actually ignored by git and is not present in your GitHub repository.

2022-09-27 15:28 UTC, cynthiainga requested changes
Hi @Anwaar12, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Used correct Github flow ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8) don't forget it in your next commit 😉 🙃 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 15:28 UTC, cynthiainga commented on index.html
> +    </section>
- [ ] I think all these parts have only two sections, and for good practice, I think it;s not better to put section tags inside the section tag. The section tag it represents a generic standalone section of the document. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info 🙃 🙃

2022-09-27 15:28 UTC, cynthiainga commented on index.html
> +      </section>
- [ ] The container of this section is a `header` tag, the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info 😉 😉
- [ ] Good job by implementing the logo but the logo is on the left and has a link (`a` tag). This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info 🙃
- [ ] The hamburger button has a `nav` tag and not all the section, please kindly fix it 🙃 🙃

2022-09-27 15:28 UTC, cynthiainga commented on index.html
> +          </li>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag), the `a` tag will let you connect your social networks with the icons, using href 😊 😉

2022-09-27 15:28 UTC, cynthiainga commented on styles.css
> +}
- [ ] Please kindly make sure your design sticks as much as possible to the Figma design, the background image has a border-radius at the left, please kindly fix it 🙃 😉 

Your design

<img width="284" alt="Screen Shot 2022-09-27 at 17 19 59" src="https://user-images.githubusercontent.com/74501523/192567342-0fac20c5-724d-4e7c-88aa-e2e26895ffe5.png">

Figma design

<img width="265" alt="Screen Shot 2022-09-27 at 17 20 39" src="https://user-images.githubusercontent.com/74501523/192567415-7185ea83-74bf-4a05-b9d5-29cbbbde86cc.png">

2022-09-27 17:59 UTC, sajid-munawar approved these changes
### Hi @Anwaar12  , 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
 ## [Optional] suggestions:
 * [ ]  Please check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @sajid-muanwar  in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 23:04 UTC, tugsem commented
Hi @Anwaar12 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a Pull Request Link, that belongs to the previous project. You should merge and close your pull requests after the project is approved. After that, start working on a new branch for new features.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-30 04:22 UTC, merged